### ISSUE TITLE
Add support for inline code completion (copilot, etc.)

### ISSUE THREAD

**Issue by failable** [meocoder31099/Serendipity-Theme-Zed#2]
<img width="475" alt="image" src="https://github.com/meocoder31099/Serendipity-Theme-Zed/assets/5475262/fd6e5b36-b923-49e3-b0a1-51722d6b602e">

**Comment by meocoder31099** [comment]
ahh, I have never used Copilot before. I will try using Copilot and support this during the weekend

**Comment by meocoder31099** [comment]
@failable could you clone this repository and install it via `Install Dev Extension`, then confirm if this resolves the issue?

**Comment by failable** [comment]
Hello, that's how it look like now, thanks for the fix.

<img width="826" alt="image" src="https://github.com/meocoder31099/Serendipity-Theme-Zed/assets/5475262/dbe38fd2-38b7-4938-b411-d23a137757c5">

**Comment by meocoder31099** [comment]
Thank you for confirming, I will open a PR to update these changes into Zed's extension repository
